-- ============================================================
-- Fact Match Load
-- Project: European Soccer Data Engineering
-- ============================================================

USE soccer_dw;

TRUNCATE TABLE fact_match;

INSERT INTO fact_match (
    match_api_id,
    source_match_id,
    date_key,
    country_key,
    league_key,
    home_team_key,
    away_team_key,
    country_id,
    league_id,
    home_team_api_id,
    away_team_api_id,
    match_date,
    season,
    stage,
    home_team_goal,
    away_team_goal,
    total_goals,
    goal_difference,
    match_result,
    home_team_points,
    away_team_points,
    is_clean_sheet_home,
    is_clean_sheet_away,
    home_player_1,
    home_player_2,
    home_player_3,
    home_player_4,
    home_player_5,
    home_player_6,
    home_player_7,
    home_player_8,
    home_player_9,
    home_player_10,
    home_player_11,
    away_player_1,
    away_player_2,
    away_player_3,
    away_player_4,
    away_player_5,
    away_player_6,
    away_player_7,
    away_player_8,
    away_player_9,
    away_player_10,
    away_player_11,
    home_player_X1,
    home_player_X2,
    home_player_X3,
    home_player_X4,
    home_player_X5,
    home_player_X6,
    home_player_X7,
    home_player_X8,
    home_player_X9,
    home_player_X10,
    home_player_X11,
    away_player_X1,
    away_player_X2,
    away_player_X3,
    away_player_X4,
    away_player_X5,
    away_player_X6,
    away_player_X7,
    away_player_X8,
    away_player_X9,
    away_player_X10,
    away_player_X11,
    home_player_Y1,
    home_player_Y2,
    home_player_Y3,
    home_player_Y4,
    home_player_Y5,
    home_player_Y6,
    home_player_Y7,
    home_player_Y8,
    home_player_Y9,
    home_player_Y10,
    home_player_Y11,
    away_player_Y1,
    away_player_Y2,
    away_player_Y3,
    away_player_Y4,
    away_player_Y5,
    away_player_Y6,
    away_player_Y7,
    away_player_Y8,
    away_player_Y9,
    away_player_Y10,
    away_player_Y11,
    b365_home_odds,
    b365_draw_odds,
    b365_away_odds,
    bw_home_odds,
    bw_draw_odds,
    bw_away_odds,
    iw_home_odds,
    iw_draw_odds,
    iw_away_odds,
    lb_home_odds,
    lb_draw_odds,
    lb_away_odds,
    ps_home_odds,
    ps_draw_odds,
    ps_away_odds,
    wh_home_odds,
    wh_draw_odds,
    wh_away_odds,
    sj_home_odds,
    sj_draw_odds,
    sj_away_odds,
    vc_home_odds,
    vc_draw_odds,
    vc_away_odds,
    gb_home_odds,
    gb_draw_odds,
    gb_away_odds,
    bs_home_odds,
    bs_draw_odds,
    bs_away_odds,
    goal_xml,
    shoton_xml,
    shotoff_xml,
    foulcommit_xml,
    card_xml,
    cross_xml,
    corner_xml,
    possession_xml
)
SELECT
    m.match_api_id,
    m.id AS source_match_id,
    d.date_key,
    c.country_key,
    l.league_key,
    home_team.team_key AS home_team_key,
    away_team.team_key AS away_team_key,
    m.country_id,
    m.league_id,
    m.home_team_api_id,
    m.away_team_api_id,
    CAST(m.`date` AS DATETIME) AS match_date,
    m.season,
    m.stage,
    m.home_team_goal,
    m.away_team_goal,
    m.home_team_goal + m.away_team_goal AS total_goals,
    m.home_team_goal - m.away_team_goal AS goal_difference,
    CASE
        WHEN m.home_team_goal > m.away_team_goal THEN 'H'
        WHEN m.home_team_goal = m.away_team_goal THEN 'D'
        ELSE 'A'
    END AS match_result,
    CASE
        WHEN m.home_team_goal > m.away_team_goal THEN 3
        WHEN m.home_team_goal = m.away_team_goal THEN 1
        ELSE 0
    END AS home_team_points,
    CASE
        WHEN m.away_team_goal > m.home_team_goal THEN 3
        WHEN m.home_team_goal = m.away_team_goal THEN 1
        ELSE 0
    END AS away_team_points,
    CASE WHEN m.away_team_goal = 0 THEN 1 ELSE 0 END AS is_clean_sheet_home,
    CASE WHEN m.home_team_goal = 0 THEN 1 ELSE 0 END AS is_clean_sheet_away,
    CAST(NULLIF(m.home_player_1, '') AS UNSIGNED) AS home_player_1,
    CAST(NULLIF(m.home_player_2, '') AS UNSIGNED) AS home_player_2,
    CAST(NULLIF(m.home_player_3, '') AS UNSIGNED) AS home_player_3,
    CAST(NULLIF(m.home_player_4, '') AS UNSIGNED) AS home_player_4,
    CAST(NULLIF(m.home_player_5, '') AS UNSIGNED) AS home_player_5,
    CAST(NULLIF(m.home_player_6, '') AS UNSIGNED) AS home_player_6,
    CAST(NULLIF(m.home_player_7, '') AS UNSIGNED) AS home_player_7,
    CAST(NULLIF(m.home_player_8, '') AS UNSIGNED) AS home_player_8,
    CAST(NULLIF(m.home_player_9, '') AS UNSIGNED) AS home_player_9,
    CAST(NULLIF(m.home_player_10, '') AS UNSIGNED) AS home_player_10,
    CAST(NULLIF(m.home_player_11, '') AS UNSIGNED) AS home_player_11,
    CAST(NULLIF(m.away_player_1, '') AS UNSIGNED) AS away_player_1,
    CAST(NULLIF(m.away_player_2, '') AS UNSIGNED) AS away_player_2,
    CAST(NULLIF(m.away_player_3, '') AS UNSIGNED) AS away_player_3,
    CAST(NULLIF(m.away_player_4, '') AS UNSIGNED) AS away_player_4,
    CAST(NULLIF(m.away_player_5, '') AS UNSIGNED) AS away_player_5,
    CAST(NULLIF(m.away_player_6, '') AS UNSIGNED) AS away_player_6,
    CAST(NULLIF(m.away_player_7, '') AS UNSIGNED) AS away_player_7,
    CAST(NULLIF(m.away_player_8, '') AS UNSIGNED) AS away_player_8,
    CAST(NULLIF(m.away_player_9, '') AS UNSIGNED) AS away_player_9,
    CAST(NULLIF(m.away_player_10, '') AS UNSIGNED) AS away_player_10,
    CAST(NULLIF(m.away_player_11, '') AS UNSIGNED) AS away_player_11,
    CAST(NULLIF(m.home_player_X1, '') AS SIGNED) AS home_player_X1,
    CAST(NULLIF(m.home_player_X2, '') AS SIGNED) AS home_player_X2,
    CAST(NULLIF(m.home_player_X3, '') AS SIGNED) AS home_player_X3,
    CAST(NULLIF(m.home_player_X4, '') AS SIGNED) AS home_player_X4,
    CAST(NULLIF(m.home_player_X5, '') AS SIGNED) AS home_player_X5,
    CAST(NULLIF(m.home_player_X6, '') AS SIGNED) AS home_player_X6,
    CAST(NULLIF(m.home_player_X7, '') AS SIGNED) AS home_player_X7,
    CAST(NULLIF(m.home_player_X8, '') AS SIGNED) AS home_player_X8,
    CAST(NULLIF(m.home_player_X9, '') AS SIGNED) AS home_player_X9,
    CAST(NULLIF(m.home_player_X10, '') AS SIGNED) AS home_player_X10,
    CAST(NULLIF(m.home_player_X11, '') AS SIGNED) AS home_player_X11,
    CAST(NULLIF(m.away_player_X1, '') AS SIGNED) AS away_player_X1,
    CAST(NULLIF(m.away_player_X2, '') AS SIGNED) AS away_player_X2,
    CAST(NULLIF(m.away_player_X3, '') AS SIGNED) AS away_player_X3,
    CAST(NULLIF(m.away_player_X4, '') AS SIGNED) AS away_player_X4,
    CAST(NULLIF(m.away_player_X5, '') AS SIGNED) AS away_player_X5,
    CAST(NULLIF(m.away_player_X6, '') AS SIGNED) AS away_player_X6,
    CAST(NULLIF(m.away_player_X7, '') AS SIGNED) AS away_player_X7,
    CAST(NULLIF(m.away_player_X8, '') AS SIGNED) AS away_player_X8,
    CAST(NULLIF(m.away_player_X9, '') AS SIGNED) AS away_player_X9,
    CAST(NULLIF(m.away_player_X10, '') AS SIGNED) AS away_player_X10,
    CAST(NULLIF(m.away_player_X11, '') AS SIGNED) AS away_player_X11,
    CAST(NULLIF(m.home_player_Y1, '') AS SIGNED) AS home_player_Y1,
    CAST(NULLIF(m.home_player_Y2, '') AS SIGNED) AS home_player_Y2,
    CAST(NULLIF(m.home_player_Y3, '') AS SIGNED) AS home_player_Y3,
    CAST(NULLIF(m.home_player_Y4, '') AS SIGNED) AS home_player_Y4,
    CAST(NULLIF(m.home_player_Y5, '') AS SIGNED) AS home_player_Y5,
    CAST(NULLIF(m.home_player_Y6, '') AS SIGNED) AS home_player_Y6,
    CAST(NULLIF(m.home_player_Y7, '') AS SIGNED) AS home_player_Y7,
    CAST(NULLIF(m.home_player_Y8, '') AS SIGNED) AS home_player_Y8,
    CAST(NULLIF(m.home_player_Y9, '') AS SIGNED) AS home_player_Y9,
    CAST(NULLIF(m.home_player_Y10, '') AS SIGNED) AS home_player_Y10,
    CAST(NULLIF(m.home_player_Y11, '') AS SIGNED) AS home_player_Y11,
    CAST(NULLIF(m.away_player_Y1, '') AS SIGNED) AS away_player_Y1,
    CAST(NULLIF(m.away_player_Y2, '') AS SIGNED) AS away_player_Y2,
    CAST(NULLIF(m.away_player_Y3, '') AS SIGNED) AS away_player_Y3,
    CAST(NULLIF(m.away_player_Y4, '') AS SIGNED) AS away_player_Y4,
    CAST(NULLIF(m.away_player_Y5, '') AS SIGNED) AS away_player_Y5,
    CAST(NULLIF(m.away_player_Y6, '') AS SIGNED) AS away_player_Y6,
    CAST(NULLIF(m.away_player_Y7, '') AS SIGNED) AS away_player_Y7,
    CAST(NULLIF(m.away_player_Y8, '') AS SIGNED) AS away_player_Y8,
    CAST(NULLIF(m.away_player_Y9, '') AS SIGNED) AS away_player_Y9,
    CAST(NULLIF(m.away_player_Y10, '') AS SIGNED) AS away_player_Y10,
    CAST(NULLIF(m.away_player_Y11, '') AS SIGNED) AS away_player_Y11,
    CAST(NULLIF(m.`B365H`, '') AS DECIMAL(6,2)) AS b365_home_odds,
    CAST(NULLIF(m.`B365D`, '') AS DECIMAL(6,2)) AS b365_draw_odds,
    CAST(NULLIF(m.`B365A`, '') AS DECIMAL(6,2)) AS b365_away_odds,
    CAST(NULLIF(m.`BWH`, '') AS DECIMAL(6,2)) AS bw_home_odds,
    CAST(NULLIF(m.`BWD`, '') AS DECIMAL(6,2)) AS bw_draw_odds,
    CAST(NULLIF(m.`BWA`, '') AS DECIMAL(6,2)) AS bw_away_odds,
    CAST(NULLIF(m.`IWH`, '') AS DECIMAL(6,2)) AS iw_home_odds,
    CAST(NULLIF(m.`IWD`, '') AS DECIMAL(6,2)) AS iw_draw_odds,
    CAST(NULLIF(m.`IWA`, '') AS DECIMAL(6,2)) AS iw_away_odds,
    CAST(NULLIF(m.`LBH`, '') AS DECIMAL(6,2)) AS lb_home_odds,
    CAST(NULLIF(m.`LBD`, '') AS DECIMAL(6,2)) AS lb_draw_odds,
    CAST(NULLIF(m.`LBA`, '') AS DECIMAL(6,2)) AS lb_away_odds,
    CAST(NULLIF(m.`PSH`, '') AS DECIMAL(6,2)) AS ps_home_odds,
    CAST(NULLIF(m.`PSD`, '') AS DECIMAL(6,2)) AS ps_draw_odds,
    CAST(NULLIF(m.`PSA`, '') AS DECIMAL(6,2)) AS ps_away_odds,
    CAST(NULLIF(m.`WHH`, '') AS DECIMAL(6,2)) AS wh_home_odds,
    CAST(NULLIF(m.`WHD`, '') AS DECIMAL(6,2)) AS wh_draw_odds,
    CAST(NULLIF(m.`WHA`, '') AS DECIMAL(6,2)) AS wh_away_odds,
    CAST(NULLIF(m.`SJH`, '') AS DECIMAL(6,2)) AS sj_home_odds,
    CAST(NULLIF(m.`SJD`, '') AS DECIMAL(6,2)) AS sj_draw_odds,
    CAST(NULLIF(m.`SJA`, '') AS DECIMAL(6,2)) AS sj_away_odds,
    CAST(NULLIF(m.`VCH`, '') AS DECIMAL(6,2)) AS vc_home_odds,
    CAST(NULLIF(m.`VCD`, '') AS DECIMAL(6,2)) AS vc_draw_odds,
    CAST(NULLIF(m.`VCA`, '') AS DECIMAL(6,2)) AS vc_away_odds,
    CAST(NULLIF(m.`GBH`, '') AS DECIMAL(6,2)) AS gb_home_odds,
    CAST(NULLIF(m.`GBD`, '') AS DECIMAL(6,2)) AS gb_draw_odds,
    CAST(NULLIF(m.`GBA`, '') AS DECIMAL(6,2)) AS gb_away_odds,
    CAST(NULLIF(m.`BSH`, '') AS DECIMAL(6,2)) AS bs_home_odds,
    CAST(NULLIF(m.`BSD`, '') AS DECIMAL(6,2)) AS bs_draw_odds,
    CAST(NULLIF(m.`BSA`, '') AS DECIMAL(6,2)) AS bs_away_odds,
    NULLIF(m.goal, '') AS goal_xml,
    NULLIF(m.shoton, '') AS shoton_xml,
    NULLIF(m.shotoff, '') AS shotoff_xml,
    NULLIF(m.foulcommit, '') AS foulcommit_xml,
    NULLIF(m.card, '') AS card_xml,
    NULLIF(m.`cross`, '') AS cross_xml,
    NULLIF(m.corner, '') AS corner_xml,
    NULLIF(m.possession, '') AS possession_xml
FROM stg_match AS m
INNER JOIN dim_date AS d
    ON d.full_date = DATE(m.`date`)
INNER JOIN dim_country AS c
    ON c.country_id = m.country_id
INNER JOIN dim_league AS l
    ON l.league_id = m.league_id
INNER JOIN dim_team AS home_team
    ON home_team.team_api_id = m.home_team_api_id
INNER JOIN dim_team AS away_team
    ON away_team.team_api_id = m.away_team_api_id;

SELECT
    'fact_match' AS table_name,
    COUNT(*) AS rows_loaded,
    MIN(match_date) AS first_match_date,
    MAX(match_date) AS last_match_date
FROM fact_match;
